### ISSUE TITLE
DataEditR does not return modified R object

### ISSUE THREAD

**Issue by frankhaege** [DillonHammill/DataEditR#59]
When starting the editor, I get the following warning messages about Font Awesome icons not being available:

> mtcars.new = data_edit(mtcars)
This Font Awesome icon ('sync') does not exist:
if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`
This Font Awesome icon ('file-download') does not exist:
if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`
This Font Awesome icon ('cut') does not exist:
if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`

The manual modifications of the dataframe are not stored in the mtcars.new object after clicking the 'Done' button, the object just returns the original mtcars dataframe

**Comment by DillonHammill** [comment]
Looks like the names of font awesome icons have changed. I will fix this up today.

**Comment by DillonHammill** [comment]
@frankhaege, I just pushed a fix to the master branch. Please pull it down and see if it works for you:
```{r}
devtools::install_github("DillonHammill/DataEditR")
```

**Comment by frankhaege** [comment]
Thanks, the warning messages are gone, but the changes I make in the editor (or in the browser) are still not returned in the R object. The changes are only retained when I save the table to a file. I also do not get the code returned when I specify code=TRUE. Maybe it is something else or I am missing something simple, but I presume the modified data and the code should be returned once I click 'Done' in the editor?

**Comment by DillonHammill** [comment]
@frankhaege, I have switched the icon library to use glyphicons instead - I think these will be more stable in terms of their naming. Please can you confirm whether the icons are visible once you have installed the latest version of DataEditR from GitHub:
```{r}
devtools::install_github("DillonHammill/DataEditR")
```

**Comment by DillonHammill** [comment]
I think you are forgetting to hit the `sync` button to transfer your changes to the `master` copy of your data prior to hitting done or save to file.
